### ISSUE TITLE
Questions about the use of code.

### ISSUE THREAD

**Issue by wssuzb** [mikle97pir/Microlensing.jl#10]
Hello, @mikle97pir 

Due to my poor knowledge in microlensing, I can't fully understand your code, and I am sorry to bother you again. 

Here is my question, I would like to use the code, only input some key parameters i.e., `κ, γ and κ∗ /κ`, and generate the magnification map, and some physical parameters related are mentioned in figures below, taken from [TK17](https://ui.adsabs.harvard.edu/abs/2018MNRAS.473...80T/abstract).  

<img width="372" alt="Screen Shot 2022-06-29 at 8 53 50 PM" src="https://user-images.githubusercontent.com/77923288/176441061-0238b48e-642b-4079-98d9-56700b5656ee.png">

<img width="586" alt="Screen Shot 2022-06-29 at 8 43 03 PM" src="https://user-images.githubusercontent.com/77923288/176438980-ce52751e-75a3-4bdf-91c0-e24cf09edf2e.png">

and then generate such magnification map (also see Figure 2 in [TK17](https://ui.adsabs.harvard.edu/abs/2018MNRAS.473...80T/abstract)):

<img width="369" alt="Screen Shot 2022-06-29 at 8 47 25 PM" src="https://user-images.githubusercontent.com/77923288/176439889-3425a968-b9a9-49ec-b61c-f52ee25b2ad3.png">

I could only figure out that the E and Λ are different format of κ and γ, and do not know how to input `κ∗ /κ` and also the `mass of stars` i.e., `<M/M_{sun}> = 0.3`.

I'd appreciate it if you could answer my childish question, and many thanks again!

Best wishes,

Zhenbo Su.

**Comment by mikle97pir** [comment]
Hello!

Define `κ_c = κ - κ∗`.
Then `E = sign(1 - κ_c + γ)` and `Λ = (1 - κ_c - γ) / (1 - κ_c + γ)`.

The stellar mass is given by the choice of the mass distribution. The distribution is given as `dmass` argument to the `generate_stars_rect` and `generate_stars_ell` functions:

```
using Distributions: Uniform
stars = generate_stars_ell(100, 15., dmass=Uniform(0.25, 0.35))
```

will generate an array of `100` stars with masses uniformly distributed between `0.25` and `0.35` solar masses in a disk of `15` solar Einstein radii.

**Comment by mikle97pir** [comment]
I took the notation from the _The perturbed Schwarzschild lens ('Chang-Refsdal lens')_  chapter of _Gravitational Lenses_ by Schneider, Ehlers and Falco.

**Comment by wssuzb** [comment]
Hello, @mikle97pir

Thanks for your answers, I will give it a try. Many many thanks again! 

Best wishes,

Zhenbo Su.
