### ISSUE TITLE
Are there any references?

### ISSUE THREAD

**Issue by wssuzb** [mikle97pir/Microlensing.jl#9]
Hello, I'm going to learn this microlensing repository but seems that I do not find any references, only the code might be a little difficult for me. So I'd appreciate it if you can tell me the reference about this repository.

Best wishes,

:)

**Comment by mikle97pir** [comment]
Hello, @wssuzb!

There is my [thesis](https://drive.google.com/file/d/10e2wtyR6-widjlWgMw0enw9QKV_cNQVN/view?usp=sharing) in Russian and partial [translation](https://drive.google.com/file/d/1EMNR9AO1UGDatsXG1WKJWl8leQEqrejT/view?usp=sharing) to English (it contains the description of the caustic search algorithm). I attach them here. Unfortunately, I have not written an article and have not finished the translation yet. I am still going to do it. I can speed up the translation process, if it is useful for you research.

Best regrads,
Misha

mikle97pir@yandex.ru

**Comment by wssuzb** [comment]
> 
Hello, 

 I think it is very useful and enough for me, and I will take some time reading your material seriously, many thanks! 

Best wishes,
Zhenbo Su
